// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yppshwznnzajxfjtwtoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwcHNod3pubnphanhmanR3dG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTM4ODQsImV4cCI6MjA3NDE2OTg4NH0.9DXaOT2OIAI-1QgtxiwG7i8xFVYb4R53y__9BJQw1M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});